[package]
name = "variables"
version = "0.1.0"
authors = ["goldencm203 <goldencm203@potsdam.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
